theme: jekyll-theme-minimal

#
# Collections
#
collections:
  pictures:
    output: true
    permalink: /photo/:slug/

#
# Default values
#
defaults:
  # _pictures
  -
    scope:
      path: ""
      type: pictures
    values:
      layout: photo
