theme: jekyll-theme-minimal
url: https://gcalvojp.github.io
baseurl: /photos

#
# Collections
#
collections:
  pictures:
    output: true
    permalink: /photo/:title/

#
# Default values
#
defaults:
  # _pictures
  -
    scope:
      path: ""
      type: pictures
    values:
      layout: photo
